# This is a config for E2B sandbox template.
# You can use template ID (uzsrfh9ddcujltpnl20u) or template name (funcode-nextjs-test) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("funcode-nextjs-test") # Sync sandbox
# sandbox = await AsyncSandbox.create("funcode-nextjs-test") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('funcode-nextjs-test')

team_id = "ee8fa6b1-509a-4dd8-b6ad-aa5e7e71752a"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "funcode-nextjs-test"
template_id = "uzsrfh9ddcujltpnl20u"
